[package]
name = "wasmhost"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "19.0.0"
anyhow = "1.0"
ron = "0.8"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4.0"
rand = "0.8"